# docker-compose.yml
version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8040:8040"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your-key
      - AWS_SECRET_ACCESS_KEY=your-secret
